---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: installing dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip 
        - virtualenv 
        - python3-setuptools

    - name: adding Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: adding Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: installing Docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted

