---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: installing dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: adding Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: adding Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: installing Docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop: [ 'docker-ce', 'docker-ce-cli' ]

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull
      
    - name: Create default containers
      docker_container:
        name: "{{ container_name }}{{ item }}"
        image: "{{ image_name }}"
        command: "{{ container_command }}"
        state: present
      with_sequence: count={{ container_count }}

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted

